long_desc_replace_tuple = (
    ("<h1", "<h3"),
    ("</h1", "</h3"),
    ("<h2", "<h4"),
    ("</h2", "</h4"),
    ("<a", "<a class='long-desc-link ldlink'"),
    ("<!DOCTYPE", ""),
    ("html>", ""),
    ("<body", ""),
    ("<div", "<article"),
    ("</div", "</article"),
    (".click", ""),
    ("bootstrap.min.css", ""),
    ("bootstrap.css", ""),
    ("jquery.min.js", ""),
    ("jquery.js", ""),
    ("fetch(", ""),
    ('window.location', ''), 
    ('document.ge', '')
)
