TOKEN_MAIN = "" # Main bot token
TOKEN_SERVER = "" # Server token
sentry_dsn = "" # Sentry DNS
pg_pwd = "" # Postgres password
csrf_secret = "" # CSRF secret
session_key = "" # Session key
oauth_client_secret = "" # OAuth Client Secret
ratelimit_bypass_key = "" # Key for bypassing ratelimit
django_secret = "" # Django secret key
recaptcha_client = "" # Recaptcha client key
recaptcha_secret = "" # Recaptxha secret
bb_add_key = "" # Botblock add bot key
bb_edit_key = "" # Botblock edit bot key
test_server_manager_key = "" # Test server manager bot (+approve, +claim etc) key
rabbitmq_pwd = "" # RabbitMQ password
