# Generated by Django 3.1.7 on 2021-03-26 07:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fladmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalulabotlist',
            name='api_token',
            field=models.TextField(default=uuid.UUID('4348a699-4598-4b04-bf11-1647c370631d')),
        ),
    ]
