# Generated by Django 3.1.7 on 2021-03-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fladmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalbot',
            name='coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalbot',
            name='banned',
            field=models.BooleanField(default=False, help_text='Use fateslist.xyz main admin console to ban or unban bots'),
        ),
        migrations.AlterField(
            model_name='historicalbot',
            name='disabled',
            field=models.BooleanField(blank=True, help_text='unused', null=True),
        ),
        migrations.AlterField(
            model_name='historicalbot',
            name='queue',
            field=models.BooleanField(default=True, help_text='Use fateslist.xyz main admin console to verify bots'),
        ),
    ]
