# Generated by Django 3.1.7 on 2021-03-26 07:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fladmin', '0002_auto_20210326_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalulabotlist',
            name='api_token',
            field=models.TextField(default=uuid.UUID('38e85b73-a18c-45be-b094-de8cdb56ba2e')),
        ),
    ]
