TOKEN_MAIN = "" # Main bot token
TOKEN_SERVER = "" # Servers bot token
session_key = "" # Session key
test_server_manager_key = "" # Test server manager bot (+approve, +claim etc) key
sentry_dsn = "" # Sentry DSN
ratelimit_bypass_key = "" # Key for bypassing ratelimit
worker_key = "" # RabbitMQ worker key
lynxfall_key = "" # Lynxfall Oauth key
discord_client_id = "" # Discord client id
discord_client_secret = "" # Discord client secret
discord_redirect_uri = "" # Discord redirect uri
