TOKEN_MAIN = "" # Main bot token
TOKEN_SERVER = "" # Servers bot token
TOKEN_DBG = "" # Debug bots token
TOKEN_MANAGER = "" # Manager bot token
session_key = "" # Session key
manager_key = "" # Test server manager bot (+approve, +claim etc) key
sentry_dsn = "" # Sentry DSN
rl_key = "" # Key for bypassing ratelimit
discord_client_id = "" # Discord client id
discord_client_secret = "" # Discord client secret
discord_redirect_uri = "" # Discord redirect uri